### ISSUE TITLE
Assignment 1 

### ISSUE THREAD

**Issue by yeshamavani** [harshsharma0510/SF-Assignments#1]
Q2. -- Difference between PUT and PATCH 

Q3. For the various response code 
you are expected to know the range and its significance
like 
400 - 499 -- client error 
500-599 -- server error 
etc

**Comment by harshsharma0510** [comment]
noted. made required addition in assignment and for my information, thank you for the input
[Assignment 1.1.pdf](https://github.com/harshsharma0510/SF-Assignments/files/12107745/Assignment.1.1.pdf)
